services:
  web:
    image: ghcr.io/kd-it/php-devcontainer/web:1728614961

    #build: docker/web
    volumes:
      - .:/app:cached
    env_file:
      - env.txt
    depends_on:
      - app
      - db

  app:
    image: ghcr.io/kd-it/php-devcontainer/app:1728614960
    #build: docker/app
    env_file:
      - env.txt
    volumes:
      - .:/app:cached
      - vendor:/app/vendor

  db:
    image: ghcr.io/densuke/mysql:main
    #build: db/build
    env_file:
      - env.txt
    volumes:
      - db_data:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s


volumes:
  db_data:
  vendor:

