services:
  web:
    # ポートフォワードをリセット(テスト環境で閉じておく)
    # ports:
    #   - 80
    depends_on:
      - app
      - db
      - selenium

  app:
    tmpfs: /app/vendor

  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - 4444 # Selenium grid server
      - 7900 # NoVNC server
    shm_size: 2gb

  db:
    tmpfs: /var/lib/mysql
